# Generated by Django 4.2.1 on 2023-06-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_artist_image'),
        ('users', '0003_remove_profile_is_staff_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='songs',
            field=models.ManyToManyField(blank=True, to='songs.song'),
        ),
    ]
