# Generated by Django 4.2.1 on 2023-05-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
        ('songs', '0003_alter_song_managers_artist_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(blank=True, to='playlists.playlist'),
        ),
    ]
