# Generated by Django 4.2.1 on 2023-05-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_song_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
