# Generated by Django 4.2.1 on 2023-06-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_alter_album_artist_alter_song_album_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
    ]
